stages:
    - pre
    - build

builder:
    stage: pre
    image: docker
    when: manual
    services:
        - name: docker:dind
          alias: docker
    variables:
        DOCKER_HOST: 'tcp://docker:2375'
    script:
        # Try to pull the image, it won't exist if this is the first time the CI has run.
        - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
        - docker pull ${CI_REGISTRY_IMAGE}/builder || true
        - docker build --cache-from ${CI_REGISTRY_IMAGE}/builder -t ${CI_REGISTRY_IMAGE}/builder .
        - docker push ${CI_REGISTRY_IMAGE}/builder

.build:
    stage: build
    image: ${CI_REGISTRY_IMAGE}/builder
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        GHIDRA_REPO: https://github.com/NationalSecurityAgency/ghidra.git
        GHIDRA_HEAD: ${TAG}
    script:
        - ./download.sh
        - cp -r flatRepo /root/flatRepo
        - unzip Downloads/gradle*.zip
        - git clone "${GHIDRA_REPO}"
        - cd ghidra 
        - git remote update
        - git checkout ${GHIDRA_HEAD}
        - git log --oneline -n 15
        - ../gradle*/bin/gradle buildGhidra
    artifacts:
        paths:
            - ghidra/build/dist/*

dev:
    extends: .build
    variables:
        TAG: origin/master

9.0.1:
    extends: .build
    when: manual
    variables:
        TAG: Ghidra_9.0.1_build

9.0.2:
    extends: .build
    when: manual
    variables:
        TAG: Ghidra_9.0.2_build

custom:
    when: manual
    extends: .build
