stages:
    - pre
    - build
    - distrib

builder:
    stage: pre
    image: docker
    services:
        - name: docker:dind
          alias: docker
    variables:
        DOCKER_HOST: 'tcp://docker:2375'
    script:
        # Try to pull the image, it won't exist if this is the first time the CI has run.
        - docker pull ${CI_REGISTRY_IMAGE}/builder || true
        - docker build --cache-from ${CI_REGISTRY_IMAGE}/builder -t ${CI_REGISTRY_IMAGE}/builder .
        - docker push ${CI_REGISTRY_IMAGE}/builder

build:
    stage: build
    image: ${CI_REGISTRY_IMAGE}/builder
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
        - ./download.sh
        - mv flatRepo /root/flatRepo
        - unzip Downloads/gradle*.zip
        - cd ghidra 
        #- ../gradle*/bin/gradle yajswDevUnpack buildGhidra cdtUnpack pyDevUnpack
        - ../gradle*/bin/gradle buildGhidra
        - zip -r ghidra_TORGO_`date +%Y%m%d`.zip ghidra.bin
    artifacts:
        paths:
            - ghidra_TORGO*.zip
